services:
  app:
    image: python:3.9-alpine
    volumes:
      - .:/app
    ports:
      - 5000:5000
    working_dir: "/app"
    entrypoint:
      "/bin/sh -c 'pip install --upgrade --no-cache-dir -r requirements.txt && python ./run.py'"

